#!/usr/bin/env python3
"""
Supplementary tab:fill-swap-pairs: the fill swap (noise fill -> real fill, OOD Dice) for every
training -> test contrast pair, i.e. the numbers behind every thin curve of fig:ladder.
Reads the same ladder_series.json files as make_per_contrast_curves.py (PANELS, load(), and its
LADDER_JSON_SUFFIX option); p = the ladder's per-contrast paired test (uncorrected, the value
that colours the pair's segment in fig:ladder).

Writes  cvpr_format_latex/sec/_suppl_fill_swap_pairs.tex   (generated -- do not hand-edit)
Usage:  .venv/bin/python paper/scripts/make_fill_swap_pairs_table.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import make_per_contrast_curves as M  # noqa: E402

OUT = HERE.parent / "cvpr_format_latex/sec/_suppl_fill_swap_pairs.tex"
NAME = {"t1in": "T1in", "t1out": "T1out", "t2spir": "T2spir", "ct": "CT", "t2w": "T2w", "T2w": "T2w",
        "T1w": "T1w", "t1w": "T1w", "bold": "BOLD", "dwi_ap": "DWI", "epi_ap": "EPI", "gre_echo1_mag": "GRE",
        "hanseg/ct": "HaN-Seg CT", "hanseg/mrt1": "HaN-Seg MR-T1", "pddca/ct": "PDDCA CT", "mri": "MRI",
        "t1n": "T1n", "t1c": "T1c", "t2f": "FLAIR", "flair": "FLAIR", "precontrast": "pre-contrast",
        "dwi": "DWI", "t1wce": "T1-CE"}
TRAIN = {"T1WCE": "T1-CE"}
GROUP = {"interface": "Interface-bounded", "no_interface": "Appearance-defined"}


def fmt_p(p: float) -> str:
    if not np.isfinite(p):
        return "--"
    if p >= 0.01:
        return f"{p:.2f}"
    m, e = f"{p:.0e}".split("e")
    return f"${m}\\!\\times\\!10^{{{int(e)}}}$"


def main():
    lines = ["% GENERATED by paper/scripts/make_fill_swap_pairs_table.py -- do not hand-edit",
             "\\begin{table}[p]", "\\centering", "\\scriptsize", "\\setlength{\\tabcolsep}{2.5pt}",
             "\\resizebox{\\linewidth}{!}{%", "\\begin{tabular}{@{}llrrrrr@{}}", "\\toprule",
             "Task & Train $\\to$ test & Noise & Real & $\\Delta$ & Rel.\\ (\\%) & $p$ \\\\", "\\midrule"]
    last_group = None
    n = 0
    order = ["Glioma", "MS", "Breast", "Abdomen", "Brain", "Mandible", "Pelvis"]   # tab:tasks order
    for task, grp, items in sorted(M.PANELS, key=lambda t: order.index(t[0])):
        if grp != last_group:
            if last_group is not None:
                lines.append("\\midrule")
            lines.append(f"\\multicolumn{{7}}{{@{{}}l}}{{\\emph{{{GROUP[grp]}}}}} \\\\")
            last_group = grp
        first = True
        for lab, rel in items:
            d = M.load(rel)
            if d is None:
                raise SystemExit(f"missing ladder {rel}")
            pc = d["fill_swap_significance"]["dice"]["per_contrast"]
            pc = dict(pc) if isinstance(pc, list) else pc
            for c in M.ood_contrasts(d):
                s = np.asarray(d["per_contrast"]["dice"][c][:M.N_RUNGS], float)
                a, b = s[M.FILL - 1], s[M.FILL]
                if not (np.isfinite(a) and np.isfinite(b)):
                    continue
                p = pc.get(c, float("nan"))
                sig = np.isfinite(p) and p < 0.05
                delta = f"${b - a:+.1f}^{{*}}$" if sig else f"${b - a:+.1f}$"
                lines.append(f"{task if first else ''} & {TRAIN.get(lab, lab)} $\\to$ {NAME.get(c, c)} & "
                             f"{a:.1f} & {b:.1f} & {delta} & ${(b - a) / a * 100:+.1f}$ & {fmt_p(p)} \\\\")
                first = False
                n += 1
    lines += ["\\bottomrule", "\\end{tabular}}",
              "\\caption{The fill swap for each training $\\to$ test contrast pair: out-of-domain Dice (\\%) "
              "of the noise-fill rung and of the real-fill rung (PALETTE alone), their difference, the "
              "difference relative to the noise-fill Dice, and the pair's paired Wilcoxon test on patients, "
              "Holm-corrected across the held-out contrasts of its setting ($^*$: $p<0.05$, the pairs "
              "colored in \\cref{fig:ladder}; \\cref{tab:dissociation} tests each setting as a whole). "
              "External cohorts are pooled with the training cohort by contrast, except Mandible, whose "
              "held-out contrasts all come from external cohorts and are listed per cohort. "
              f"{n} pairs.}}",
              "\\label{tab:fill-swap-pairs}", "\\end{table}"]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({n} pairs)")


if __name__ == "__main__":
    main()
