# @package model
generator:
  gen_version: v26_1
  apply_guidance_blur: false
  sigmoid_scale: 4.0
  target_generator:
    _target_: src.target_generators.V26EMParcellationChunkTargetGenerator
  loss_weights:
    edge: 30.0
    tv: 0.0
    range: 100.0
    guidance_blurred: 15.0
    guidance_sharp: 0.0
  guidance_perturber:
    _target_: src.guidance_perturbers.MildGaussianGuidancePerturber
    sigma: 1.0
    kernel_size: 9
    background_threshold: 0.02

segmenter:
  use_generator: true
  gen_version: v26_1
  aug_prob_val: 1.0
  compile_synthesis: false
  apply_guidance_blur: false
  out_channels: 4
  sigmoid_scale: 4.0
  target_generator:
    _target_: src.target_generators.V26EMParcellationChunkTargetGenerator
  guidance_perturber:
    _target_: src.guidance_perturbers.MildGaussianGuidancePerturber
    sigma: 1.0
    kernel_size: 9
    background_threshold: 0.02
  resolution_resampler:
    zoom_min: 0.3
    zoom_max: 1.5
    anisotropy_prob: 0.5
