defaults:
  - defaults
  - _self_

generator:
  gen_version: v17_lpci
  target_generator:
    _target_: src.target_generators.LegacyChunkTargetGenerator
  guidance_perturber: null

segmenter:
  use_generator: true
  gen_version: v17_lpci
  target_generator:
    _target_: src.target_generators.LegacyChunkTargetGenerator
  guidance_perturber: null
