defaults:
  - defaults
  - _self_

generator:
  gen_version: v18_4
  apply_guidance_blur: false
  target_generator:
    _target_: src.target_generators.V18_4CoalescingSplineTargetGenerator
    coarse_grid_size: [8, 8, 8]
    background_threshold: 0.01
    num_quantiles: 100
    max_sample_size: 100000
  guidance_perturber: null

segmenter:
  use_generator: true
  gen_version: v18_4
  aug_prob_val: 1.0
  compile_synthesis: false
  apply_guidance_blur: false
  target_generator:
    _target_: src.target_generators.V18_4CoalescingSplineTargetGenerator
    coarse_grid_size: [8, 8, 8]
    background_threshold: 0.01
    num_quantiles: 100
    max_sample_size: 100000
  guidance_perturber: null
