#!/usr/bin/env python3
"""
Generate the ladder's rung 4.5 (FLAT fill) wrappers, 2026-10-08, by COPYING each setting's rung-4 lblvor wrapper
(scripts/cluster/rung4_lblvor/make_wrappers.py output) and changing ONLY the transform config and the method name:

  AUGLAB_PARAMS_GPU_JSON  transform_params_gpu_baseline_kmeans_label_remap_voronoi_lblvor_spatialDA_train050.json
                       -> transform_params_gpu_baseline_kmeans_label_remap_voronoi_flatfill_spatialDA_train050.json
  METHOD / LOG_DIR        <...>_lblvor  ->  <...>_flatfill

WHY (Paul, 2026-10-08): the fill swap noise (rung 4) -> real (rung 5) could come from REMOVING NOISE rather than ADDING
TEXTURE. Rung 4.5 fills every region of PALETTE's partition with its target mean (no noise, no texture) and keeps
PALETTE's own label step, so 4.5 -> 5 differs ONLY by the within-region texture term alpha_c * (x - mean_c), and
4 -> 4.5 is noise removal (plus the label step: SynthSeg-style Voronoi noise refill in rung 4 vs PALETTE's affine
re-remap of the current image). Config verified before launch: scripts/cluster/rung45_flat/verify_flatfill.py.

Trainer, epochs, data, env and checkpoint selection (plain AugLabDefault trainer, checkpoint_best on real validation)
are those of the rung-4 lblvor wrapper by construction.

Usage:  .venv/bin/python scripts/cluster/rung45_flat/make_wrappers.py [--write]
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
T = REPO / "benchmark/02_tasks"
OLD_CFG = "transform_params_gpu_baseline_kmeans_label_remap_voronoi_lblvor_spatialDA_train050.json"
NEW_CFG = "transform_params_gpu_baseline_kmeans_label_remap_voronoi_flatfill_spatialDA_train050.json"
OLD_SUFFIX, NEW_SUFFIX = "_lblvor", "_flatfill"

# (task dir, dataset, contrast tag) -- the 16 paper ladder settings + pansegdata (not in the paper; added 2026-10-09 as the
# boundary-defined negative control for the noise-vs-texture split)
SETTINGS = [
    ("brain_tumor", "brats2024-glioma", "t1n"), ("brain_tumor", "brats2024-glioma", "t2w"),
    ("brain_tumor", "brats2024-glioma", "t2f"), ("brain_tumor", "brats2024-glioma", "t1c"),
    ("brain_healthy", "on-harmony", "t1w"), ("brain_healthy", "on-harmony", "t2w"), ("brain_healthy", "on-harmony", "dwi_ap"),
    ("brain_ms", "open-ms", "flair"), ("brain_ms", "open-ms", "t1w"),
    ("abdomen_healthy", "chaos", "t1in"), ("abdomen_healthy", "chaos", "t2spir"),
    ("mandible_healthy", "toothfairy2", "cbct"),
    ("breast_cancer", "ispy2", "t1wce"), ("breast_cancer", "ispy2", "t2w"),
    ("pelvis_healthy", "totalseg-pelvic", "ct"), ("pelvis_healthy", "totalseg-pelvic", "mri"),
    ("pancreas_disease", "pansegdata", "t1wce"), ("pancreas_disease", "pansegdata", "t2w"),
]


def lblvor_wrapper(d: Path, tag: str) -> Path:
    w = [p for p in d.glob(f"04_*_train_{tag}_*_lblvor.sh") if "rung4_lblvor/make_wrappers.py" in p.read_text()]
    assert len(w) == 1, f"{d}: expected one generated {tag} lblvor wrapper, got {w}"
    return w[0]


def derive(src: str) -> tuple[str, str, str]:
    m = re.search(r'^METHOD="([^"]+)"', src, re.M); assert m, "no METHOD line"
    old_method = m.group(1); assert old_method.endswith(OLD_SUFFIX), old_method
    method = old_method[: -len(OLD_SUFFIX)] + NEW_SUFFIX
    trainer = re.search(r'^TRAINER="([^"]+)"', src, re.M).group(1)
    out = []
    for line in src.splitlines():
        if not line.lstrip().startswith("#"):
            if line.startswith("METHOD="):
                line = f'METHOD="{method}"'
            elif "LOG_DIR=" in line:
                assert old_method in line, line
                line = line.replace(old_method, method)
            elif "AUGLAB_PARAMS_GPU_JSON=" in line and "AUGLAB_VAL" not in line:
                assert OLD_CFG in line, f"unexpected rung-4 config: {line}"
                line = line.replace(OLD_CFG, NEW_CFG)
        out.append(line)
    text = "\n".join(out) + "\n"
    assert NEW_CFG in text and f'METHOD="{method}"' in text and OLD_CFG not in text and OLD_SUFFIX not in \
        "\n".join(l for l in text.splitlines() if not l.lstrip().startswith("#"))
    return text, method, trainer


def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--write", action="store_true"); a = ap.parse_args()
    for task, ds, tag in SETTINGS:
        d = T / task / ds / f"5_scripts_{ds}" / "04_train"
        w4 = lblvor_wrapper(d, tag)
        src = w4.read_text()
        body = src.split("\n", 1)[1]
        body = "\n".join(l for l in body.splitlines() if not l.startswith("# GENERATED by") and
                         not l.startswith("# ladder rung 4 (+Voronoi") and not l.startswith("# otherwise identical to"))
        text, method, trainer = derive(body)
        existing = [p for p in d.glob("04_*.sh") if f"rung45_flat/make_wrappers.py from {w4.name} " in p.read_text()]
        if existing:
            print(f"exists   {existing[0].relative_to(REPO)}"); continue
        nums = sorted(int(p.name[3:5]) for p in d.glob("04_[0-9][0-9]_*.sh"))
        free = [i for i in range(max(nums) + 1, 100)] or [i for i in range(100) if i not in nums][::-1]
        n = free[0]
        name = f"04_{n:02d}_train_{tag}_{method}.sh" if tag not in method else f"04_{n:02d}_train_{method}.sh"
        header = (f"#!/usr/bin/env bash\n# GENERATED by scripts/cluster/rung45_flat/make_wrappers.py from {w4.name} (do not hand-edit):\n"
                  f"# ladder rung 4.5 (FLAT fill: every region of PALETTE's partition at its target mean, PALETTE's label step, no\n"
                  f"# noise, no texture; {NEW_CFG});\n"
                  f"# otherwise identical to {w4.name} (trainer {trainer}: checkpoint_best on real validation).\n")
        out = d / name
        print(f"{'write' if a.write else 'would '} {out.relative_to(REPO)}  METHOD={method}  TRAINER={trainer}")
        if a.write:
            out.write_text(header + text)


if __name__ == "__main__":
    main()
